const routes = {
  auth: {
    login: "/auth/login",
    forget_password: "/auth/forget_password",
    register: "/auth/register",
    verify_otp: "/auth/verify-otp",
  },
  dashboard: {
    home: "/dashboard",
  },
  notification: {
    list: "/notifications",
  },
  vehicles: {
    list: "/vehicles",
    details: "details/:vehicleId",
    details_nav: (vehicleId: string) => `details/${vehicleId}`,
    on_map: "map/:vehicleId",
    on_map_nav: (vehicleId: string) => `map/${vehicleId}`,
    add: "add-vehicle",
    edit: "edit-vehicle/:vehicleId",
    edit_nav: (vehicleId: string) => `edit-vehicle/${vehicleId}`,
    bird_eye_view: "/bird-eye-view/:vehicleId",
    bird_eye_view_nav: (vehicleId: string) => `/bird-eye-view/${vehicleId}`,
    fences: "/fences/:deviceId/:vehicleId",
    fences_nav: (deviceId: string, vehicleId: string) => `/fences/${deviceId}/${vehicleId}`,
    trips: "/trips/:vehicleId",
    trips_nav: (vehicleId: string) => `/trips/${vehicleId}`,
    req_service: "req-service/:vehicleId",
    req_service_nav: (vehicleId: string) => `req-service/${vehicleId}`,
  },
  reports: {
    reports: "/reports/:vehicleId",
    reports_nav: (vehicleId: string) => `/reports/${vehicleId}`,
    collision_report: "collision-report/:vehicleId",
    collision_report_nav: (vehicleId: string) => `collision-report/${vehicleId}`,
    forklift_utilization_report: "utilization-report/:vehicleId",
    forklift_utilization_report_nav: (vehicleId: string) => `utilization-report/${vehicleId}`,
    forklift_breakdown_report: "breakdown-report/:vehicleId",
    forklift_breakdown_report_nav: (vehicleId: string) => `breakdown-report/${vehicleId}`,
    over_speeding_report: "over-speeding-report/:vehicleId",
    over_speeding_report_nav: (vehicleId: string) => `over-speeding-report/${vehicleId}`,
    driver_performance_report: "driver-performance-report/:vehicleId",
    driver_performance_report_nav: (vehicleId: string) => `driver-performance-report/${vehicleId}`,
    forklift_maintenance_report: "forklift-maintenance-report/:vehicleId",
    forklift_maintenance_report_nav: (vehicleId: string) =>
      `forklift-maintenance-report/${vehicleId}`,
    idling_report: "idling-report/:vehicleId",
    idling_report_nav: (vehicleId: string) => `idling-report/${vehicleId}`,
    ignition_report: "ignition-report/:vehicleId",
    ignition_report_nav: (vehicleId: string) => `ignition-report/${vehicleId}`,
    history_report: "history-report/:vehicleId",
    history_report_nav: (vehicleId: string) => `history-report/${vehicleId}`,
    driver_activity_report: "driver-activity-report/",
  },
  services: {
    list: "/services",
    details: "details/:serviceId",
    details_nav: (serviceId: string) => `details/${serviceId}`,
  },
  drivers: {
    list: "/drivers",
    create: "add-driver",
    create_activity: "add-activity",
    edit: "edit-driver/:driverId",
    edit_nav: (driverId: string) => `edit-driver/${driverId}`,
    details: "details/:driverId",
    details_nav: (driverId: string) => `details/${driverId}`,
    activity: "activity/:driverId",
    activity_nav: (driverId: string) => `activity/${driverId}`,
  },
  poi: {
    list: "/poi",
  },
  settings: {
    home: "/settings",
    change_password: "change-password",
    driver_working_time: "driver-working-time",
    vehicle_icons: "vehicle-icons",
    checklist_management: "checklist-management",
    app_theme: "app-theme",
  },
  help: {
    home: "/help",
  },
  about: {
    home: "/about",
  },
};
export { routes };
